// <auto-generated />
namespace PrsServerApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedothercontrollers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedothercontrollers));
        
        string IMigrationMetadata.Id
        {
            get { return "201806281722078_added other controllers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
